### ISSUE TITLE
Got a hell of Crash!

### ISSUE THREAD

**Issue by blueberry6401** [nicegram/Telegram-iOS#102]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Sometimes, when unlock my phone, I got tons of crash messages like this video

https://user-images.githubusercontent.com/7337535/106215211-0730e180-6203-11eb-99d3-72497d891d7a.mov

I submit crash report several times, so you guys may take a look.

### Screenshots and Videos 
Remove, if not applicable

### Environment
**Device:** `iPhone X 64G`

**iOS version**: `14.4` and some older versions

**App version:** `7.3.1 (1430) from TestFlight. And some older versions.`

**Comment by Kylmakalle** [comment]
Known. Due to nicegram does not work in background. You might install stable version if you need. 
Read https://nicegram.app/7.0
