### ISSUE TITLE
[Feature request] Show instant edit media button on all media, not only on 'my' media

### ISSUE THREAD

**Issue by mahenzon** [nicegram/Telegram-iOS#103]
There's a button to instantly edit shared media, but only media shared by 'me'
Add this button for any media (photo, at least)
(Maybe there's a reason why it's not )

![IMG_DD4105459A1F-1](https://user-images.githubusercontent.com/20804158/106395450-6402e680-6413-11eb-9205-af666337d06c.jpeg)
![IMG_E738DFB3D49F-1](https://user-images.githubusercontent.com/20804158/106395597-189d0800-6414-11eb-9d36-790c3c712191.jpeg)

**Comment by BROSVORN** [comment]
https://github.com/twitter/twemoji/issues/469

**Comment by mahenzon** [comment]
works for any photo now (maybe it was server-side, or just fixed in another update)
