### ISSUE TITLE
[Feature Request] Support proxy with shadowsocks or vmess

### ISSUE THREAD

**Issue by EkkoG** [nicegram/Telegram-iOS#114]
Since MTProxy is easy to be identified, if Nicegram has built-in shadowsocks or vmess proxy support, It will be more convenient to use Nicegram.

Shadowsocks and vmess protocol are stable, with almost no breaking changes. I think it's ok and no tech limit to add this feature.

**Comment by jordon1002** [comment]
Information cannot be translated when using built-in agents, severely affecting the experience. Please fix this bug as soon as possible.
