### ISSUE TITLE
Unnamed notifications go non-stop

### ISSUE THREAD

**Issue by AngryJKirk** [nicegram/Telegram-iOS#119]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I was using Nicegram for a few months. Few days later I decided to switch back to original Telegram app. I didn't like it again and moved back to Nicegram. 

But now I have issues with notifications. All the time I got notification with a title "Name" and message "You have a new message", but I don't have any messages and when I press the notifications it does nothing. 

I can get something like 300 or 500 of this everyday. Reinstall does not work.
### Expected Behavior
No unknown notifications.

### Actual Behavior
Tons of notifications just appears

### Steps to Reproduce
Just wait some time.

### Screenshots and Videos 
Though they look normal, they do not get you to the unread message. All normal notifications are displayed with text and name of the sender.
![image](https://user-images.githubusercontent.com/16938543/143249538-2067f762-93ac-44b3-a94c-9c2b0d8500ae.png)

### Environment
**Device:** `iPhone 13 Pro MAX`

**iOS version**: `15.1.1`

**App version:** `latest?`

**Comment by AngryJKirk** [comment]
More pictures

![image](https://user-images.githubusercontent.com/16938543/143251145-081ee475-0f80-45e2-8581-b015e1e64362.png)
![image](https://user-images.githubusercontent.com/16938543/143251176-6d6dc611-b478-4c33-92ab-9218769fffb3.png)

**Comment by AngryJKirk** [comment]
And everything works fine, e.g. Desktop Telegram and Web

**Comment by Kylmakalle** [comment]
Notifications are sent by Telegram servers - and Nicegram cannot influence them in any way. https://bugs.telegram.org/c/174/40

**Comment by Rithari** [comment]
This has been fixed according to their bug tracking, however the issue persists.

**Comment by AngryJKirk** [comment]
I can confirm the issue is still there. Since I created this issue I have been using the official Telegram and it's fine there. 

A week ago or so I tried to switch back to Nicegram and the issue hasn't gone.

**Comment by WYStudioEx** [comment]
Hello, may I ask how to solve this, I am also a third party application, can provide client repair code? Thank you very much.
