### ISSUE TITLE
VoiceOver on M1 Mac: Scrolling is broken.

### ISSUE THREAD

**Issue by TheQuinbox** [nicegram/Telegram-iOS#120]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
The Mac has (surprisingly) no accessible Telegram clients. I was quite excited when I saw Nicegram. But... It's not perfect. Scrolling has some really, really weird issues. If I'm in a chat and get another message in that chat, I can't erad it without going out of the chat and back in, which is not officient with VoiceOver.
### Expected Behavior
Messages should scroll with the VoiceOver cursor, also known as keyboard focus.
### Actual Behavior
They... Well um... Don't.
### Steps to Reproduce
1. Start VoiceOver
2. Open a chat, and send or receive a message in that chat.
3. Try to get over to it with the VoiceOver cursor.

### Environment
**Device:** MacBook Air M1 (2020). 1 TB Storage, 16 GB RAM

**macOS version**: 12.1

**App version:** Latest in App Store (I think it's 8.2)?

**Comment by ssheleg** [comment]
Nicegram will have a stable desktop version
