### ISSUE TITLE
Official support for M1 Macs?

### ISSUE THREAD

**Issue by TheQuinbox** [nicegram/Telegram-iOS#121]
While it's possible to install Nicegram onto an M1 Mac, the experience is far from perfect. For example, there's no quick way to get out of a chat, jump to the edit field, etc. These are huge dealbreakers for someone like me who uses a screen reader. Also, the chat slist doesn't go away when you click on a chat. It should.
Here's what I think needs to be done:
* Command+W to close a chat.
* #120
* Chats list disappears when selecting a chat.
* Maybe command+J? To jump directly to the new message field.

**Comment by ssheleg** [comment]
The Mac commands are not supported in iOS app
