### ISSUE TITLE
All options are enabled. But some of channels don't work.

### ISSUE THREAD

**Issue by vadimszzz** [nicegram/Telegram-iOS#122]
### Checklist
- [*] I am reporting an issue in existing functionality that does not work as intended
- [*] I've searched for existing GitHub issues

### Description
All options are enabled. But some of channels don't work.
![CE9831A4-C7A8-4316-B237-DE2FA8FCD4D5](https://user-images.githubusercontent.com/92526019/147075915-a3480f52-419f-42c3-9cc8-3040ecbfe258.png)
![8C4E5CB0-209B-4111-944C-1952F5BD5310](https://user-images.githubusercontent.com/92526019/147075936-57fb41aa-fb28-41eb-8781-0eb3c81ee0f5.png)

### Expected Behavior
![A0BCA483-C425-4A87-B8EF-7F0CCFA95F29](https://user-images.githubusercontent.com/92526019/147076550-104336e2-1db7-4596-bc5a-297ee00ec225.jpeg)

### Actual Behavior
![B27A4C96-78BC-4089-AB9A-62F0A41FE5D6](https://user-images.githubusercontent.com/92526019/147076579-0d614282-9fc1-4743-864d-6cf0f6fa7b99.jpeg)

### Screenshots and Videos 
🙄

**Comment by Kylmakalle** [comment]
https://nicegram.app/unblock/#additional-notes
> Some chats may be blocked globally by Telegram—there’s no way to unblock them.

**Comment by vadimszzz** [comment]
> Some chats may be blocked globally by Telegram—there’s no way to unblock them
It's not impossible. You just don't want to fix it.

**Comment by vadimszzz** [comment]
Reopen the issue, it's a bug anyway.

**Comment by vadimszzz** [comment]
Thinking that something is impossible means that you have lack of education.

**Comment by Kylmakalle** [comment]
Telegram uses [restrictionReason](https://core.telegram.org/constructor/restrictionReason) parameter to block chats and individual messages.

Some chats may be blocked on individual platform, such as on `ios`. That means server will provide restrictionReason flag for client to block the content on end-device. And that's what Nicegram changes in source code - it ignores some restrictionReasons options for user_id if toggle is active on website or in the bot.

Some chats may be blocked with `platform=all` option, that means it won't be accessible on any platform. Telegram servers will also mock messages for non owners of chat to make chat completely unavailable for any other user.
Owner of chat has an ability to delete inappropriate content and _probably_ recover it via Telegram Support.

Here's an example, If you've properly unblocked chats in Nicegram, you will still see mocked messages in this channel with restriction_reason `porn-all`
https://t.me/pretty

More info on possible restriction_reasons: https://telegra.ph/Telegram-restriction-reasons-09-20
Bot for testing restriction_reason flags: https://t.me/CheckRestrictionsBot

Now you should be educated enough.

**Comment by vadimszzz** [comment]
Chanel that's on screenshot is available on other platforms.

**Comment by Kylmakalle** [comment]
@vadimszzz You may share your solution in private for a discussion. https://t.me/Kylmakalle
