### ISSUE TITLE
All options are enabled. But some of channels don't work.

### ISSUE THREAD

**Issue by vadimszzz** [nicegram/Telegram-iOS#123]
### Checklist
- [*] I am reporting an issue in existing functionality that does not work as intended
- [*] I've searched for existing GitHub issues

### Description
All options are enabled. But some of channels don't work.
![CE9831A4-C7A8-4316-B237-DE2FA8FCD4D5](https://user-images.githubusercontent.com/92526019/147075915-a3480f52-419f-42c3-9cc8-3040ecbfe258.png)
![8C4E5CB0-209B-4111-944C-1952F5BD5310](https://user-images.githubusercontent.com/92526019/147075936-57fb41aa-fb28-41eb-8781-0eb3c81ee0f5.png)

### Expected Behavior
![A0BCA483-C425-4A87-B8EF-7F0CCFA95F29](https://user-images.githubusercontent.com/92526019/147076550-104336e2-1db7-4596-bc5a-297ee00ec225.jpeg)

### Actual Behavior
![B27A4C96-78BC-4089-AB9A-62F0A41FE5D6](https://user-images.githubusercontent.com/92526019/147076579-0d614282-9fc1-4743-864d-6cf0f6fa7b99.jpeg)

**Comment by vadimszzz** [comment]
Don't close unfixed  bugs.

**Comment by Kylmakalle** [comment]
Duplicate https://github.com/nicegram/Telegram-iOS/issues/122
