### ISSUE TITLE
nicegram crashes on new Apple Watch SE with Watch OS 8.3

### ISSUE THREAD

**Issue by SonGokuSSJ** [nicegram/Telegram-iOS#124]
### Checklist
- [X] I am reporting an issue in existing functionality that does not work as intended
- [X] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I just got a Apple Watch SE on Christmas and I installed nicegram. When I start nicegram it closes / crashes the app (it still seem to be running in the background as I can open the App menu on the Watch and close the app. Trying to open the app again moves it back to the background. I also tried to uninstall nicegram on the Watch and install it again. Still the same behavior.

### Expected Behavior
Upon starting nicegram it should show my chats.

### Actual Behavior
It just crashes / sets it to the background. Bringing it to the front sets it again to the background.

### Steps to Reproduce
1. Open nicegram
2.  -
3.  -

### Environment
**Device:** `Apple Watch SE`

**WatchOS version**: `8.1` and `8.3`

**App version:** `8.2.2` (latest from Apple Appstore).

### Additional Info
Telegram has the same problem and only because of that issue I tried nicegram to find out, that the same issue persists here. The corresponding Github Issue on Telegram is here: 

https://github.com/TelegramMessenger/Telegram-iOS/issues/691

nanogram (native WatchOS App) works flawlessly (probably because it does not need to connect to the iPhone at all).

**Comment by Kylmakalle** [comment]
Related to https://github.com/TelegramMessenger/Telegram-iOS/issues/691 as you've mentioned.

Nanogram is a standalone watch app with completely different source code.

**Comment by SonGokuSSJ** [comment]
The Telegram Chat (which is used to communicate new updates) is probably the culprit. Deleting the chat messages there solved the crash problem. The chat messages itself take ages to load (and do not seem to finish loading), but that is a different problem.
