### ISSUE TITLE
"You have a new message" spam when utilising Telegram Desktop.

### ISSUE THREAD

**Issue by Rithari** [nicegram/Telegram-iOS#125]
> This has been fixed according to their bug tracking, however the issue persists.
> 
> To apply the fix on your device for the default Telegram app, an app update was required, which leads me to believe that there is something that needs to be done on the Nicegram fork's end to apply the fix.
> 
> 
> See [this comment ](https://github.com/TelegramMessenger/Telegram-iOS/issues/690#issuecomment-1022420431)in reference - I am trying to figure out where exactly this supposed fix is, so that I may redirect it to the issue in question. In the meantime, if anyone that is actually qualified, unlike me, would mind taking a look themselves I think this could be accelerated and solved within days.

_Originally posted by @Rithari in https://github.com/nicegram/Telegram-iOS/issues/119#issuecomment-1022413464_

As can be seen above, the issue is still present in the latest Nicegram versions, suggesting that a fix on the fork is required. I believe dismissing this as a Telegram server-side issue is an oversight.

Nicegram v. 8.3.1 (1711)
iOS 15.2.1 
Latest Telegram desktop version available as of Jan 26th
macOS 12.1
16" M1 Pro MacBook Pro

**Comment by Kylmakalle** [comment]
https://github.com/nicegram/Telegram-iOS/issues/119
