### ISSUE TITLE
A lot of features that was in Nicegram 6.* missing in 7.*; I understand that everything is moving forward but

### ISSUE THREAD

**Issue by vadimszzz** [nicegram/Telegram-iOS#133]
Could you provide please TestFlight release with 6.* version? There is no other way to downgrade your app without jailbreak.
It was ultra cool app with tons of tweaks but after 7.* update you started to do everything again from scratch and honestly a lot of people love more previous way of folders managing then new telegram's native. I hope it's not hard for you to create TestFlight release with old app :)

**Comment by ssheleg** [comment]
Hi,

We apologize for such an unstable version, the update is already under review, you can also check the update in TF https://testflight.apple.com/join/XnH6ZNVq

**Comment by vadimszzz** [comment]
You didn’t get it

**Comment by vadimszzz** [comment]
The problem is not in bugs. We need the old version, it was handy

**Comment by vadimszzz** [comment]
The only way to install old ipa file without jailbreak is to provide it as a separate application in the appstore or if you don’t want to publish it you can publish it using another testflight.
I hope you finally understand me
