### ISSUE TITLE
weird thing with proxy setting

### ISSUE THREAD

**Issue by timmyz** [nicegram/Telegram-iOS#14]
hi  @Kylmakalle,  
i tried with your guidance, still not working. please see the following screenshots.
![image](https://user-images.githubusercontent.com/795528/61614921-6a999500-ac97-11e9-8616-512994a3e723.png)
![image](https://user-images.githubusercontent.com/795528/61614927-6d948580-ac97-11e9-96ec-9b26912ba6e0.png)
when i input the proxy Info, it seems working with ping response. but if i click the ‘use proxy’ button, it will keep the circle running ‘waiting for network’ forever

**Comment by Kylmakalle** [comment]
I don't reliable for any proxies and connection issues, sorry.
