### ISSUE TITLE
[Feature request] Secure telegram p2p

### ISSUE THREAD

**Issue by krizka** [nicegram/Telegram-iOS#16]
What about making telegram fully secure and implement p2p encryption on top of the protocol? Two nicegrams can then handshake and be truly secure.

**Comment by Kylmakalle** [comment]
You can use already implemented secret chats

According to [Telegram TOS](https://core.telegram.org/api/terms)
> It is forbidden to force users of other Telegram clients to download your app in order to view certain messages and content sent using your app.

**Comment by krizka** [comment]
I agree. But secret chats are not widely used in the current implementation. Also, the functionality I'm proposing is not forcing users to anything. It is an optional choice, and not prevent messaging with default telegram.

**Comment by Kylmakalle** [comment]
So this function will not be popular either

**Comment by krizka** [comment]
It will be on by default for nicegram-to-nicegram user, and also could populate it as first truly secure Telegram

**Comment by Kylmakalle** [comment]
So you can still use secret chats ¯\_(ツ)_/¯

**Comment by krizka** [comment]
Maybe you could create vote somewhere. Maybe I could.
