### ISSUE TITLE
[Feature Request] Button for retrieving closed pinned message.

### ISSUE THREAD

**Issue by Kylmakalle** [nicegram/Telegram-iOS#3]
• In group info, put an option called “pinned message” and when you tap on it, it will scroll to the message.  That way if you accidentally close it, you can still get to it again.

[@nicegramchat/191](https://t.me/nicegramchat/191)

**Comment by tak1nu** [comment]
if Telegram X in Android has it, why not us?, only another button in action bar (or whatever is called), and ready! 😁, I don't think that there's should be a problem adding the button

**Comment by Kylmakalle** [comment]
Released in [Build 15](https://github.com/nicegram/Telegram-iOS/commit/ad8d1867245dfb25bec76dfb000dd80ec2bd86d9#diff-1c94d18b25a7aad0e28d822886902b66)
