### ISSUE TITLE
[BUG]Nicegram's badge problem

### ISSUE THREAD

**Issue by MatrixLau** [nicegram/Telegram-iOS#36]
If nicegram isn't alive in background, when nicegram recive a new message, it will notify as usual in banner or something, but icon's badge in desktop wont update the number until you open nicegram.

**Comment by Kylmakalle** [comment]
1. https://github.com/nicegram/Telegram-iOS/issues/8#issuecomment-495305781
2. https://github.com/TelegramMessenger/Telegram-iOS/issues/178
