### ISSUE TITLE
Notification problems

### ISSUE THREAD

**Issue by TekuSP** [nicegram/Telegram-iOS#8]
If I mute person, notifications about messages are still showing up.
Only so there is new message, not from who or content of message. Bugs with people, not with groups/channels.

IPhone 8. Version 5.6-20, IOS 12.3

Replication test: Mute a person, minimize nicegram and let that person send you message.

**Comment by Kylmakalle** [comment]
It's a known issue and can't be fixed client-side. Only by Telegram Team. I'm already in contact with support and dev team to resolve this issue. Bage counter is also affected, it doesn't update in background (this doesn't related to 5.6 version, it was a problem previously too)

More info [here](https://twitter.com/nicegramapp/status/1128016308287811585)

**Comment by kode54** [comment]
Sorry, I didn't realize my issue was the same as this one. My issue was with unmuted notifications not appearing.

**Comment by Kylmakalle** [comment]
> notifications not appearing.

As long as notifications are delivered by Telegram Apple Push Notification Servers, it's not Nicegram's issue and it's impossible to fix client-side.


I tried, really.
