### ISSUE TITLE
Group icons overhang when > 4 in archived folder

### ISSUE THREAD

**Issue by canineontoast** [nicegram/Telegram-iOS#80]
this issue goes away after tapping on the first available non-archived chat, but persists when you tap on any other chat. In my case, if I tap on the top chat, it goes away, but not if I tap on the one below it.

![80A9B7E1-5BC3-4CFC-B587-527104BAF27D](https://user-images.githubusercontent.com/59421809/77616334-621cec80-6eff-11ea-9ffd-221ebaa63d35.jpeg)

**Comment by Kylmakalle** [comment]
Folder icons are not adapted to custom font size

**Comment by Kylmakalle** [comment]
Telegram folders is a successor of Nicegram folders
