### ISSUE TITLE
Notifications are still displayed even after messages have been read on a different device

### ISSUE THREAD

**Issue by prog666** [nicegram/Telegram-iOS#88]
Reproduction steps: receive a message, read it in telegram desktop, check notifications on your ios device, messages are still there.

**Comment by prog666** [comment]
Even worse, sometimes after you unlock the iphone, you get notifications as if they just came. Unfortunately I have to go back to original telegram client

**Comment by Kylmakalle** [comment]
https://github.com/TelegramMessenger/Telegram-iOS/issues/178
